name: manage-your-labels
on: [push, workflow_dispatch]
jobs:
  mirror-labels:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    name: manage-your-labels
    steps:
      - uses: actions/checkout@v2
      - uses: silpheel/manage-your-labels@main
